# 使用Alpine Linux作为基础镜像
FROM alpine:latest

# 执行更新和安装所需软件包
RUN apk update
RUN apk add --no-cache x11vnc xvfb supervisor wget
RUN wget https://github.com/novnc/noVNC/archive/refs/tags/v1.2.0.tar.gz
RUN tar -zxvf v1.2.0.tar.gz /usr/share/novnc
RUN wget https://github.com/novnc/websockify/archive/master.tar.gz
RUN tar -zxvf master.tar.gz /usr/share/novnc/utils/websockify
RUN chmod +x /usr/share/novnc/utils/*.sh

# 安装X11的必要组件
RUN apk add --no-cache xorg-server xorg-xauth xterm

# 设置X11环境变量
ENV DISPLAY=:0

# 创建普通用户
RUN adduser -D user
USER user

# 设置工作目录
WORKDIR /home/user

# 创建supervisord.conf配置文件
RUN echo "[supervisord]" > /etc/supervisord.conf && \
    echo "nodaemon=true" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:xvfb]" >> /etc/supervisord.conf && \
    echo "command=Xvfb :0 -screen 0 1024x768x24" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:x11vnc]" >> /etc/supervisord.conf && \
    echo "command=x11vnc -display :0 -forever -passwd 1128 -shared" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:websockify]" >> /etc/supervisord.conf && \
    echo "command=/usr/share/novnc/utils/launch.sh --vnc localhost:5900" >> /etc/supervisord.conf

# 启动supervisor以同时运行x11vnc和websockify
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
