# 使用Alpine Linux作为基础镜像
FROM alpine:latest

# 执行更新和安装所需软件包
RUN apk update && \
    apk add --no-cache x11vnc xvfb xterm novnc

# 设置X11环境变量
ENV DISPLAY=:0

# 启动Xvfb
CMD ["Xvfb", ":0", "-screen", "0", "1024x768x24"]

# Expose noVNC port
EXPOSE 6080

# 启动x11vnc和noVNC
CMD ["sh", "-c", "x11vnc -display :0 -forever -passwd 1128 -shared & /usr/share/novnc/utils/launch.sh --vnc localhost:5900"]
